/*
 *  build.rs
 *
 *  VCW - The Vinyl Capture Workstation
 *  (c) 2026 Stue Hunter
 *
 *  Stamps the build date into the binary and paints the README's version badge.
 *
 *  MIT License - see the header in any Rust source file for the full text.
 */

//! Stamps the build date into the binary, and repaints the README's badge.
//!
//! A version on its own does not answer the question people actually ask about
//! a build they are holding, which is "is this the one from Tuesday". Cargo
//! hands out the version and nothing else, so the date has to come from here.
//!
//! This lives in `vcw-contract` because every other crate in both workspaces
//! depends on it, so there is exactly one build script and it cannot be out of
//! step with the binary it describes. The workspace root is a *virtual*
//! manifest with no package in it, so a `build.rs` there is never run at all.
//!
//! `SOURCE_DATE_EPOCH` is honoured first, because that is the variable a
//! reproducible-build environment sets and a package that rebuilds to
//! different bytes every time is a package nobody can verify. Without it, now.
//!
//! No `chrono`, no `time`. The conversion below is twelve lines and the
//! alternative is a dependency in the build graph of the one crate every other
//! crate in the workspace depends on.

use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

fn main() {
    // Re-run when the crate does. Without this the date is whenever this file
    // last changed, which is never, and a build date that does not move is
    // worse than no build date at all.
    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-env-changed=SOURCE_DATE_EPOCH");

    let seconds = std::env::var("SOURCE_DATE_EPOCH")
        .ok()
        .and_then(|set| set.parse::<i64>().ok())
        .unwrap_or_else(|| {
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map_or(0, |since| since.as_secs() as i64)
        });

    let built = iso(seconds / 86_400);
    let version = std::env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".to_owned());

    println!("cargo:rustc-env=VCW_BUILT={built}");

    badge(&version, &built);
}

/// Repaints `assets/version.svg`, the badge at the top of the README.
///
/// VRipr's badge was a hand-edited SVG, which is why it shipped three releases
/// with the previous version painted on it. Generating it from the version
/// Cargo already knows means the only way it can be wrong is if nothing was
/// built, and the thing it is attached to is a build.
fn badge(version: &str, built: &str) {
    let Ok(manifest) = std::env::var("CARGO_MANIFEST_DIR") else {
        return;
    };
    // `crates/contract` -> the workspace root. A published or vendored copy of
    // this crate has no such directory, and a build script that invented one
    // would be writing into somebody else's tree.
    let out = Path::new(&manifest).join("../../assets/version.svg");
    if !out.parent().is_some_and(Path::is_dir) {
        return;
    }

    let label = format!("VCW v{version} | Built: {built}");
    // The width tracks the label, because a fixed one clipped "v0.10.0" the
    // day a two-digit minor arrived. 6.1 px a character at 10 px DejaVu Serif,
    // plus the chevrons and the padding.
    let width = label.len() * 61 / 10 + 46;
    let svg = format!(
        r##"<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by crates/contract/build.rs. Do not edit by hand. -->
<svg width="{width}" height="20" role="img" aria-label="{label}"
   version="1.1" xmlns="http://www.w3.org/2000/svg">
  <title>{label}</title>
  <defs>
    <linearGradient id="sheen" x1="0" y1="0" x2="0" y2="20"
       gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#ffffff" stop-opacity=".12" />
      <stop offset="1" stop-color="#000000" stop-opacity=".18" />
    </linearGradient>
    <clipPath id="rounded">
      <rect width="{width}" height="20" rx="3" fill="#ffffff" />
    </clipPath>
  </defs>
  <g clip-path="url(#rounded)">
    <rect width="{width}" height="20" fill="#1d3b3d" />
    <rect width="{width}" height="20" fill="url(#sheen)" />
    <text x="{mid}" y="14" xml:space="preserve"
       style="font-size:10px;font-family:'DejaVu Serif',serif;text-anchor:middle;fill:#ffd700;stroke:#be8400;stroke-width:0.5;stroke-linejoin:round">&gt;&gt; {label} &lt;&lt;</text>
  </g>
</svg>
"##,
        mid = width / 2,
    );

    // Only rewrite when it actually changes, so a rebuild on the same day does
    // not touch the mtime or show up as a dirty working tree.
    if std::fs::read_to_string(&out).is_ok_and(|current| current == svg) {
        return;
    }
    // Best effort: the tree is read-only for a vendored build, and a stale
    // badge is better than a failed one.
    if let Err(error) = std::fs::write(&out, svg) {
        println!("cargo:warning=could not repaint assets/version.svg: {error}");
    }
}

/// A day number since 1970-01-01 as `YYYY-MM-DD`.
///
/// Hinnant's civil-from-days: shift the epoch to 0000-03-01 so a leap day is
/// the last day of the year rather than a hole in the middle of it, then the
/// 400-year cycle divides exactly and the month length is a line of integer
/// arithmetic rather than a table.
fn iso(days: i64) -> String {
    let shifted = days + 719_468;
    let era = shifted.div_euclid(146_097);
    let of_era = shifted.rem_euclid(146_097);
    let year_of_era = (of_era - of_era / 1460 + of_era / 36_524 - of_era / 146_096) / 365;
    let day_of_year = of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let shifted_month = (5 * day_of_year + 2) / 153;
    let day = day_of_year - (153 * shifted_month + 2) / 5 + 1;
    let month = if shifted_month < 10 {
        shifted_month + 3
    } else {
        shifted_month - 9
    };
    let year = year_of_era + era * 400 + i64::from(month <= 2);
    format!("{year:04}-{month:02}-{day:02}")
}
