#!/usr/bin/env bash
#
#  version-badge.sh
#
#  VCW - The Vinyl Capture Workstation
#  (c) 2026 Stue Hunter
#
#  Regenerates the README's version badge from the workspace version.
#
# MIT License - see the header in any Rust source file for the full text.
#
# The badge in VRipr's README is a hand-edited SVG, which is why VRipr shipped
# three releases with the previous version painted on it. This one is generated
# from `Cargo.toml` and the current date, so the only way it can be wrong is if
# nobody ran it - and the release script does.
#
#   tools/version-badge.sh            # write assets/version.svg
#   tools/version-badge.sh --check    # fail if it is not current
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/assets/version.svg"

version=$(sed -n 's/^version = "\(.*\)"$/\1/p' "$root/Cargo.toml" | head -1)
[ -n "$version" ] || { echo "no version in Cargo.toml" >&2; exit 2; }
built=$(date -u +%Y-%m-%d)
label="VCW v$version | Built: $built"

# The width tracks the label, because a fixed one clipped "v0.10.0" the day a
# two-digit minor arrived. 6.1 px a character at 10 px DejaVu Serif, plus the
# chevrons and the padding.
width=$(( ${#label} * 61 / 10 + 46 ))
mid=$(( width / 2 ))

cat > "$out" <<SVG
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by tools/version-badge.sh. Do not edit by hand. -->
<svg width="$width" height="20" role="img" aria-label="$label"
   version="1.1" xmlns="http://www.w3.org/2000/svg">
  <title>$label</title>
  <defs>
    <linearGradient id="sheen" x1="0" y1="0" x2="0" y2="20"
       gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#ffffff" stop-opacity=".12" />
      <stop offset="1" stop-color="#000000" stop-opacity=".18" />
    </linearGradient>
    <clipPath id="rounded">
      <rect width="$width" height="20" rx="3" fill="#ffffff" />
    </clipPath>
  </defs>
  <g clip-path="url(#rounded)">
    <rect width="$width" height="20" fill="#1d3b3d" />
    <rect width="$width" height="20" fill="url(#sheen)" />
    <text x="$mid" y="14" xml:space="preserve"
       style="font-size:10px;font-family:'DejaVu Serif',serif;text-anchor:middle;fill:#ffd700;stroke:#be8400;stroke-width:0.5;stroke-linejoin:round">&gt;&gt; $label &lt;&lt;</text>
  </g>
</svg>
SVG

if [ "${1:-}" = "--check" ]; then
    # The date moves every day, so only the version is checked: the question a
    # release asks is "does the badge say what we are shipping", not "was it
    # regenerated this morning".
    grep -q "VCW v$version " "$out" || {
        echo "assets/version.svg does not say v$version; run tools/version-badge.sh" >&2
        exit 1
    }
fi
echo "assets/version.svg: $label"
